name: Build iOS Unsigned IPA

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS (Unsigned)
      run: flutter build ios --no-codesign

    - name: Create IPA
      run: |
        mkdir -p Payload
        cp -r build/ios/iphoneos/Runner.app Payload/
        zip -r Runner.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: unsigned-ipa
        path: Runner.ipa
